### ISSUE TITLE
lodash.merge 4.6.1 => 4.6.2

### ISSUE THREAD

**Issue by Blejzer** [stdarg/config-js#5]
Hi,

Can you please update lodash.merge version to 4.6.2?

Thanks
                                                   
=== npm audit security report ===                                                                                                       
Lvl.: High         -     Prototype Pollution 
Package:         -     lodash.merge 
Patched in      >=4.6.2 

Dependency of  config-js 
Path           config-js > lodash.merge

**Comment by stdarg** [comment]
Yes, thanks.

**Comment by Blejzer** [comment]
Thank you, great work!
